### ISSUE TITLE
Ubuntu unittests failing

### ISSUE THREAD

**Issue by davidpablocohn** [davidpablocohn/openrvdas#37]
Primarily (but not exclusively) seems to be ordering problems:

rvdas@ubuntu16:~/openrvdas$ python3 -m unittest discover
...........F.......E....F...........................F.Fs..s.....
======================================================================
ERROR: test_tail_true (logger.readers.test_text_file_reader.TestTextFileReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rvdas/openrvdas/logger/readers/test_text_file_reader.py", line 96, in test_tail_true
    self.assertEqual(line, reader.read())
  File "/home/rvdas/openrvdas/logger/readers/text_file_reader.py", line 149, in read
    time.sleep(self.retry_interval)
  File "/home/rvdas/openrvdas/logger/readers/test_network_reader.py", line 59, in _handler
    raise ReaderTimeout
logger.readers.test_network_reader.ReaderTimeout

======================================================================
FAIL: test_udp (logger.readers.test_network_reader.TestNetworkReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rvdas/openrvdas/logger/readers/test_network_reader.py", line 74, in test_udp
    self.assertEqual(line, reader.read())
AssertionError: 'f1 line 2' != 'f1 line 1'
- f1 line 2
?         ^
+ f1 line 1
?         ^

======================================================================
FAIL: test_json (logger.transforms.test_parse_nmea_transform.TestParseNMEATransform)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rvdas/openrvdas/logger/transforms/test_parse_nmea_transform.py", line 90, in test_json
    self.assertEqual(result, JSON[i])
AssertionError: '{"message_type": "$HEROT", "fields": {"Gyro[79 chars] {}}' != '{"data_id": "gyr1", "message_type": "$HEROT[79 chars] {}}'
- {"message_type": "$HEROT", "fields": {"Gyro1RateOfTurn": 2.9}, "data_id": "gyr1", "timestamp": 1510275607.737, "metadata": {}}
+ {"data_id": "gyr1", "message_type": "$HEROT", "timestamp": 1510275607.737, "fields": {"Gyro1RateOfTurn": 2.9}, "metadata": {}}

======================================================================
FAIL: test_all_files (logger.writers.test_composed_writer.TestComposedWriter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rvdas/openrvdas/logger/writers/test_composed_writer.py", line 73, in test_all_files
    self.assertEqual(line, f2_line)
AssertionError: 'f1 line 1' != ''
- f1 line 1
+ 

======================================================================
FAIL: test_prefix (logger.writers.test_composed_writer.TestComposedWriter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rvdas/openrvdas/logger/writers/test_composed_writer.py", line 97, in test_prefix
    self.assertEqual('p2 p1 ' + line, f2_line)
AssertionError: 'p2 p1 f1 line 1' != ''
- p2 p1 f1 line 1
+ 

----------------------------------------------------------------------
Ran 64 tests in 28.267s

FAILED (failures=4, errors=1, skipped=2)

**Comment by davidpablocohn** [comment]
Fixed by 7b37525 and 028da1b . I *think*.
